before_install:
  - sudo apt-get update
install:
  - 
  - sudo apt-get install collectd libdbd-mysql-perl
  - sudo collectd -h
  - sudo mkdir /etc/collectd/managed_config
  - sudo cp managed_config/* /etc/collectd/managed_config/
  - sudo cp collectd.conf /etc/collectd/
  - sudo sed -i -e "s#/etc/collectd.d/#/etc/collectd/#" /etc/collectd/collectd.conf
  - perl -MCPAN -e install Bundle::DBD::mysql

script: sudo collectd -f
